#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Obsidian"
path = "~/Seafile/Obsidian/"
startup_command = "nvim ."

[[session]]
name = "home (~)"
path = "~"
disable_startup_command = true

[[session]]
name = "sesh"
path = "~/.config/sesh"
startup_command = "nvim ~/.config/sesh/sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "hello_teacher"
path = "~/Projects/hello_teacher/"
windows = ["ssh2", "air", "minio", "postgres", "translate"]

[[window]]
name = "ssh2"
startup_script = "ssh matthias@unraidvm"

[[window]]
name = "air"
startup_script = "air"

[[window]]
name = "minio"
startup_script = "minio server ~/minio-data --address :9000 --console-address :9001"

[[window]]
name = "translate"
startup_script = "uvx libretranslate --host 0.0.0.0 --port 5000"

[[window]]
name = "postgres"
startup_script = "psql -U postgres -d hello_teacher"

[[session]]
name = "tmux"
path = "~/dotfiles/tmux/.config/tmux/"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/.config/tmux/tmux.conf"

[[session]]
name = "cpms_migration_v2"
path = "~/Projects/cpms_migration_v2/"
windows = ["ssh1", "prefect"]

[[window]]
name = "ssh1"
startup_script = "clear && ssh sysadmin@10.211.76.5"

[[window]]
name = "prefect"
startup_script = "uv run prefect server start"
