# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Chrome (default profile), exec, uwsm app -- google-chrome-stable --profile-directory="Default"
bindd = SUPER SHIFT, B, Chrome (profile 1), exec, uwsm app -- google-chrome-stable --profile-directory="Profile 1"
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, S, Music, exec, omarchy-launch-or-focus spotify
# bindd = SUPER SHIFT, N, Editor, exec, code
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
# bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm-app -- obsidian"
# bindd = SUPER SHIFT, O, Obsidian Session, exec, $terminal sesh connect Obsidian
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- 1password

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-or-focus dcal
# bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
unbind = SUPER CTRL, D
bindd = SUPER CTRL, D, Omarchy menu, exec, omarchy-menu
# Bind Super+D to launch Walker
unbind = SUPER, D
unbind = SUPER, SPACE 
unbind = SUPER ALT, SPACE 
bindd = SUPER, D, Walker, exec, uwsm app -- walker
bind = SUPER, SPACE, exec, ~/.config/hypr/scripts/monitor_auto_move.sh
bind = SUPER ALT, SPACE, exec, ~/.config/hypr/scripts/enable_laptop_profile.sh

# Move focus with SUPER + arrow keys
unbind = SUPER, L
unbind = SUPER, H
unbind = SUPER, J
# unbind = SUPER, K
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d

# origally, SUPER K was show key bindings


bindd = SUPER SHIFT, h, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, l, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, k, Swap window up, swapwindow, u
bindd = SUPER SHIFT, j, Swap window down, swapwindow, d

# Overwrite Share (SUPER CTRL, S) to launch workspace apps
unbind = SUPER CTRL, S
bindd = SUPER CTRL, S, Launch workspace apps, exec, ~/.local/bin/launch-workspace-apps

# dissable super tab to switch workspaces
unbind = SUPER, TAB
unbind = SUPER SHIFT, TAB
unbind = SUPER CTRL, TAB

# unbind the old group browsing
unbind = SUPER ALT, TAB, Next window in group, changegroupactive, f
unbind = SUPER ALT SHIFT, TAB, Previous window in group, changegroupactive, b
# bind the SUPER TAB group browsing
bindd = SUPER, TAB, Next window in group, changegroupactive, f
bindd = SUPER SHIFT, TAB, Previous window in group, changegroupactive, b

